-- Sample SQL Queries
-- These example queries demonstrate how to retrieve and analyze data
-- from the Airport Database System.

SELECT F.FLIGHT_ID, SUM (T.PRICE) AS TOTAL_SALES 
FROM TICKET T
JOIN FLIGHT F ON  T.FLIGHT_ID = F.FLIGHT_ID
GROUP BY F.FLIGHT_ID;


SELECT E.EMPLOYEE_NAME, E.POSITION_A, D.DEPARIMENT_NAME, E. SALARY 
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID

  
SELECT D.Department_Name, COUNT(E.Employee_ID) AS TotalEmployees
FROM Department D
JOIN Employee E ON D.Department_ID = E.Department_ID
GROUP BY D.Department_Name;


SELECT P.PASSENGER_NAME, T.SEAT_NUMBER, B.PNR, F.DEPARTURE_AIRPORT, F.ARRIVAL_AIRPORT, F.DATE_A
FROM PASSENGER P
JOIN TICKET T ON P.PASSENGER_ID = T.PASSENGER_ID
JOIN BOARDING B ON T.TICKET_ID = B.TICKET_ID
JOIN FLIGHT F ON F.FLIGHT_ID " T.FLIGHT_ID
ORDER BY F.DATE_A


